In [1]:
from numpy import *
data = array([[1,2,3],[1,2,3]])
print(data)

[[1 2 3]
 [1 2 3]]


In [3]:
data.shape

(2, 3)

In [4]:
zeros_matrix = zeros((1,2))
print(zeros_matrix)

[[0. 0.]]


In [5]:
ones_matrix = ones((1,2))
print(ones_matrix)

[[1. 1.]]


In [6]:
rand_matrix = random.randint(10,size=(10,5))
print(rand_matrix)

[[5 5 1 9 1]
 [6 5 4 7 5]
 [4 7 8 4 9]
 [3 6 1 0 8]
 [8 7 5 6 6]
 [6 1 9 4 3]
 [3 0 0 3 3]
 [5 7 4 8 3]
 [2 9 8 0 7]
 [5 0 1 1 3]]


In [8]:
col_vector = random.randint(10,size=(10,1))
print(col_vector)

[[4]
 [9]
 [3]
 [5]
 [4]
 [9]
 [7]
 [7]
 [8]
 [0]]


In [10]:
print(col_vector[0])

[4]


In [11]:
col_vector[0] = 1100
print(col_vector)

[[1100]
 [   9]
 [   3]
 [   5]
 [   4]
 [   9]
 [   7]
 [   7]
 [   8]
 [   0]]


In [13]:
print(rand_matrix[0,0])

5


In [17]:
print (rand_matrix[:,0:1])

[[5]
 [6]
 [4]
 [3]
 [8]
 [6]
 [3]
 [5]
 [2]
 [5]]


In [18]:
print(rand_matrix[0:1,:])

[[5 5 1 9 1]]


In [20]:
print(rand_matrix[0:1,1:4])

[[5 1 9]]


In [21]:
flattenned = rand_matrix.flatten()
print(flattenned)

[5 5 1 9 1 6 5 4 7 5 4 7 8 4 9 3 6 1 0 8 8 7 5 6 6 6 1 9 4 3 3 0 0 3 3 5 7
 4 8 3 2 9 8 0 7 5 0 1 1 3]


In [24]:
rand_matrix_2 = random.randint(10,size=(5,2))
dot_product = rand_matrix.dot(rand_matrix_2)
print(dot_product)

[[ 60 103]
 [ 82 127]
 [113 144]
 [ 82  46]
 [105 134]
 [ 53 132]
 [ 21  45]
 [ 87 126]
 [111  96]
 [ 25  39]]
